# Generated by Django 2.0.5 on 2018-05-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
    ]
